.pois_colours <-
  c("black" = "#000000",
    "blue" ="#183172",
    "aqua" = "#00706C",
    "red" = "#E84D22",
    "yellow" = "#F7B500",
    "peach" = "#F7DDAD",
    "grey" = "#616161",
    "purple" = "#821C65",
    "green" = "#1C5108", 
    "legacy_red" = "#ff2500",
    "legacy_blue" = "#0433ff",
    "legacy_green" = "#008b00",
    "legacy_brown" = "#a52a2a",
    "legacy_gray" = "#707f90",
    "legacy_orchid" = "#da70d6",
    "legacy_lightblue" = "#87cefa",
    "legacy_aquamarine" = "#458b74",
    "legacy_orange" = "#cd8500",
    "legacy_purple" = "#a034f0",
    "cblind_orange" = "#D55E00",
    "cblind_blue" = "#0072B2",
    "cblind_green" = "#009E73",
    "cblind_mango" = "#E69F00",
    "cblind_yellow" = "#F0E442",
    "cblind_pink" = "#CC79A7",
    "cblind_lightblue" = "#56B4E9",
    "pois_blue1" = "#759dbe",
    "pois_blue2" = "#92bde3",
    "pois_blue3" = "#abcbe7")


.pois_palettes <- list(
  legacy1 = c("black", "legacy_red", "legacy_blue", "legacy_green", "legacy_orange",
              "legacy_gray"),
  legacy2 = c("black", "legacy_red", "legacy_blue", "legacy_green", "legacy_orange",
              "legacy_gray", "legacy_purple"),
  legacy3 = c("black", "legacy_red", "legacy_blue", "legacy_green", "legacy_brown",
              "legacy_gray", "legacy_orchid", "legacy_lightblue","aquamarine",
              "legacy_orange"),
  colours = c("black", "blue", "aqua", "red", "yellow", "peach", "purple", "grey", "green"),
  cool = c("blue", "green"),
  hot = c("red", "yellow"))

.max_integer <- 2147483647L
